# Frontend Dockerfile
FROM hub.megan.ir/node:18-alpine

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm config set registry https://hub.megan.ir/npm
RUN npm install
COPY frontend/ ./
RUN npm run build

EXPOSE 4173
CMD ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "4173"]
